name: tests-courses

on:
  pull_request:
    paths:
      - "courses/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd courses && npm install && npm run test:ci
